### ISSUE TITLE
Is it any plan to support Visual studio 2013?

### ISSUE THREAD

**Issue by gagmeng** [vchirikov/GoToDnSpy#1]
Is it any plan to support Visual studio 2013? Thanks

**Comment by verysimplenick** [comment]
I don't have VS 2013 for now. I'll soon see what can be done

**Comment by verysimplenick** [comment]
For now I don't know how add some

**Comment by verysimplenick** [comment]
GoToDnSpy use Roslyn for code analysis, some features has [breaking changes in Project System](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/breaking_changes_visual_studio_next.md)
I think it's hard to port to older VS. (maybe easy to port to VS 2015)

**Comment by gagmeng** [comment]
Thanks. Maybe the best way is to update visual stuido.
