### ISSUE TITLE
Could not load file or assembly Microsoft.CodeAnalysis

### ISSUE THREAD

**Issue by Vijay-Nirmal** [vchirikov/GoToDnSpy#10]
Whenever I select "GoTo dnSpy" in tools it shows below error

![image](https://user-images.githubusercontent.com/24755596/76764699-4c9b1a80-67bb-11ea-9438-64f8ddad85d8.png)

**Comment by vchirikov** [comment]
VS version?

**Comment by Vijay-Nirmal** [comment]
Visual Studio 2019 - Version 16.3.8

**Comment by vchirikov** [comment]
Sorry but I won't install previous VS versions for testing. The versioning of VS and vsix dependencies is completely unclear to me, so I am developing and testing the plugin only on latest VS. But you can build this plugin by yourself for your VS version, for this fork the repo and try downgrade versions of these`PackageReferences`:

https://github.com/vchirikov/GoToDnSpy/blob/0aa511c9ef9ec15d9de3cf3fde4a4111893e4fee/src/GoToDnSpy/GoToDnSpy.csproj#L50-L59

After this bump version here:

https://github.com/vchirikov/GoToDnSpy/blob/0aa511c9ef9ec15d9de3cf3fde4a4111893e4fee/src/GoToDnSpy/source.extension.vsixmanifest#L4

And hit "Debug" (VS experimental instance will be started with your own build of GoToDnSpy).
Fusion log will help you to found reasons of `TypeLoadException` and figure out how to fix them.
You can google it, or simple use something like https://github.com/awaescher/Fusion/

I will close this issue after your feedback.

**Comment by Vijay-Nirmal** [comment]
Updating Visual Studio 2019 works!!

**Comment by vchirikov** [comment]
Nice :)

**Comment by dandrejvv** [comment]
But then why is it advertised to also work on Visual Studio 2017 on the VS marketplace? I ran into the exact same issue.
