### ISSUE TITLE
The 'GoToDnSpyPackage' package did not load correctly when opening property window of visual studio

### ISSUE THREAD

**Issue by Vijay-Nirmal** [vchirikov/GoToDnSpy#11]
I am getting The 'GoToDnSpyPackage' package did not load correctly when opening property window of visual studio. Here is the [ActivityLog file](https://github.com/vchirikov/GoToDnSpy/files/4343037/ActivityLog.zip).

This issue is in Visual Studio 2017 Version 15.9.11

Errow popup
![image](https://user-images.githubusercontent.com/24755596/76849233-08ffe980-686b-11ea-8275-de5cc2fdd0d0.png)

Property window of visual studio
![image](https://user-images.githubusercontent.com/24755596/76850180-dbb43b00-686c-11ea-96aa-875ec675012f.png)

ActivityLog File
![ActivityLog File](https://user-images.githubusercontent.com/24755596/76849848-34370880-686c-11ea-9f04-c633643856b2.png)

**Comment by vchirikov** [comment]
Discussion in https://github.com/vchirikov/GoToDnSpy/issues/10

**Comment by Vijay-Nirmal** [comment]
#10 and this a completely different issue. This can't even load the extension and the other is happening only when running

**Comment by vchirikov** [comment]
VS 2017 was the first version where the plugin worked, but now 2017 is not supported. I don't want create a special edition for 2017 (like Roslynator 2017, Roslynator 2019 etc), so I'll remove VS 2017 from vsix manifest at all.

**Comment by vchirikov** [comment]
If you want you can make PR with build for VS 2017.

**Comment by Vijay-Nirmal** [comment]
Ooo I didn't know it is not supported in 2017 but it is still listed as supported for 2017.

![image](https://user-images.githubusercontent.com/24755596/76991834-4306e380-6970-11ea-955a-bff5ac5d2215.png)

**Comment by vchirikov** [comment]
Yes, this is my mistake. I'll edit manifest to exclude 2017 and older 2019 builds.

**Comment by JereckNET** [comment]
The extension is still listed as compatible with VS2017 (and it was installed in both VS2017 and VS2019 when I launched the vsix installer).

**Comment by vchirikov** [comment]
![https://marketplace.visualstudio.com/items?itemName=VladimirChirikov.GoToDnSpy](https://user-images.githubusercontent.com/40987940/93325711-611aa700-f820-11ea-8cf5-07f3bdf8969e.png)

Updated.
