### ISSUE TITLE
support visual studio 2022 preview

### ISSUE THREAD

**Issue by InvalidCast44** [vchirikov/GoToDnSpy#13]
hi

would you please support visual studio 2022 preview?

thanks

**Comment by vchirikov** [comment]
Hi, yep, maybe I'll do it at the weekend

**Comment by vchirikov** [comment]
Done
[vs2022](https://marketplace.visualstudio.com/items?itemName=VladimirChirikov.GoToDnSpy)  
[vs2019](https://marketplace.visualstudio.com/items?itemName=VladimirChirikov.GoToDnSpy2019)
