### ISSUE TITLE
dnSpy not opening

### ISSUE THREAD

**Issue by mrpmorris** [vchirikov/GoToDnSpy#15]
First, thank you for sharing your work!!!!

I have my `dnSpy path` set as follows `C:\Program Files\dnSpy-net-win64\dnspy.exe` but when I right-click an identifier and try to view it in dnSpy it instead opens a browser and takes me to source code online.

**Comment by vchirikov** [comment]
yep, it's a feature :)
For the BCL libraries (they are ref assemblies anyway) the plugin opens sources from `source.dot.net`.

**Comment by vchirikov** [comment]
If you want you can add a config flag to disable this or rebuild the plugin without this:

https://github.com/vchirikov/GoToDnSpy/blob/dbd386c3dba37ca99606537a1241ff4ddc6dcc1e/src/GoToDnSpy/GoToDnSpy.cs#L268-L288

**Comment by mrpmorris** [comment]
Can't it open the binary that will be used by my app?

**Comment by vchirikov** [comment]
Most of the time msbuild works with runtime/aspnetcore [ref assemblies](https://docs.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies), they look like this:

![image](https://user-images.githubusercontent.com/40987940/178156429-249b5051-2e87-46f5-bcc0-0f8dbf2fb920.png)

So there is no point to disassembly it. (body of the methods are `throw null`).  
For nupkg / your code it will open dnSpy as usual.

p.s. it also was reported here: #2

**Comment by mrpmorris** [comment]
When the app is built though surely I get concrete versions? Could those be opened?

**Comment by vchirikov** [comment]
Maybe, but I don't want to spend time on this, because I no longer use VS as my main IDE. In any case if you really need this feel free to make a PR with this.
