### ISSUE TITLE
nuget packages vs2022

### ISSUE THREAD

**Issue by luigui501** [vchirikov/GoToDnSpy#17]
I have not been able to get my Visual Studio 2022 to install MailKit nuget packages. The Browse tab does not show anything, it is as if it does not connect to the network to download them. Please can you help me?

**Comment by vchirikov** [comment]
It's not related to this plugin, sorry, try to read [docs about how to report problem with VS](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022)
