### ISSUE TITLE
dnSpy is opened with reference assemblies for .net framework code

### ISSUE THREAD

**Issue by smax48** [vchirikov/GoToDnSpy#2]
When I try to open dnSpy from VS 2017 on some declarations that are part of the .net framework, dnSpy is launched with reference assemblies instead of those in GAC. As a result of that, the decompiled code is empty (contains just declarations).
My project targets .net framework 4.5.2

**Comment by verysimplenick** [comment]
I see same behavior with netstandart projects. I'll see what i can do

**Comment by verysimplenick** [comment]
@smax48 I can't update VSIX on vs marketplace for now (MS added new "create flow" for VS add-ons => I don't have my extensions on a new dashboard).
I will update the extension as soon as I can.

**Comment by smax48** [comment]
ok, thanks a lot! 
Will try the updated version when it becomes available

**Comment by verysimplenick** [comment]
@smax48 updated
