### ISSUE TITLE
I got an error after set the dnspy path.

### ISSUE THREAD

**Issue by zy-zero** [vchirikov/GoToDnSpy#5]
Version: 1.0.6
![gotodnspy_error](https://user-images.githubusercontent.com/23359848/47079541-5d4b0800-d238-11e8-988e-88c2e1cf4e47.png)

The path of my PC is “D:\dnSpy\dnSpy.exe”

**Comment by vchirikov** [comment]
I think I must update VS dependencies and rebuild vsix for latest VS.
Thanks for report, I ping you then it's will be done.

**Comment by FK68** [comment]
Hello,
have you updated the dependencies ?

**Comment by vchirikov** [comment]
Yep
