### ISSUE TITLE
Issue when i want to start 

### ISSUE THREAD

**Issue by FK68** [vchirikov/GoToDnSpy#7]
![issue](https://user-images.githubusercontent.com/47403900/52381877-7c81d580-2a73-11e9-945d-a21ee7db6c49.png)

**Comment by vchirikov** [comment]
I think you trying to run goto dnspy command without opened code window (or maybe without focus), so code can't get `IWpfTextView`, I added additional check for this and remove dependency on window focus.
Feel free reopen issue if see this error again in 1.0.8 version.

**Comment by vchirikov** [comment]
Duplicate #5

**Comment by FK68** [comment]
Thanks, it worked fine
